# This is a basic ci workflow

name: ci

# Trigger workflow on push or pull request events but only for master
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        cmake \
        xorg-dev \
        libglu1-mesa-dev \
        freeglut3-dev \
        libxi-dev \
        libxrandr-dev \
        imagemagick

    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: tests
      run: |
        cd build
        source/tests

    - name: test render
      run: |
          build/source/raytracer source/tests/simple2.sdf
          convert image.ppm render.png

    - name: upload test render
      uses: actions/upload-artifact@v2
      with:
          path: render.png

